#X Headers
X-Frame-Options = SAMEORIGIN
X-Content-Type-Options = nosniff
X-XSS-Protection = 1; mode=block

#CORS Headers
Access-Control-Allow-Origin = https://myodysi.com
Vary = Origin

#Policy Headers
Content-Security-Policy =   base-uri 'none'; \
                            form-action 'self'; \
                            frame-ancestors 'self'; \
                            default-src 'none'; \
                            frame-src 'self'; \
                            font-src 'self'; \
                            manifest-src 'self'; \
                            object-src 'self'; \
                            child-src 'self' blob:; \
                            style-src 'self' 'unsafe-inline' https://api.mapbox.com; \
                            img-src 'self' https://maps.gstatic.com https://restcountries.eu blob: data:; \
                            script-src 'self' 'nonce-76bacd65' 'unsafe-eval' https://api.mapbox.com https://maps.googleapis.com https://storage.googleapis.com; \
                            connect-src 'self' https://api.mapbox.com https://events.mapbox.com https://maps.googleapis.com https://maps.gstatic.com https://restcountries.eu;
Strict-Transport-Security = max-age=31536000; includeSubDomains; preload
Feature-Policy =    autoplay 'none'; \
                    accelerometer 'none'; \
                    camera 'none'; \
                    document-domain 'none'; \
                    encrypted-media 'none'; \
                    gyroscope 'none'; \
                    magnetometer 'none'; \
                    microphone 'none'; \
                    midi 'none'; \
                    payment 'none'; \
                    picture-in-picture 'none'; \
                    sync-xhr 'none'; \
                    usb 'none'; 
Referrer-Policy = no-referrer
Expect-CT = max-age=86400

#Cache Headers
cache-control = no-cache
expires = 0
pragma = no-cache
